SELECT A.AUTHOR_ID,
       AUTHOR_NAME,
       CATEGORY,
       TOTAL_SALES
FROM AUTHOR AS A
INNER JOIN
(
    SELECT B.AUTHOR_ID,
           B.CATEGORY,
           SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
    FROM BOOK AS B
    INNER JOIN BOOK_SALES AS BS ON B.BOOK_ID = BS.BOOK_ID
    WHERE BS.SALES_DATE LIKE '2022-01%'
    GROUP BY B.AUTHOR_ID, B.CATEGORY
) AS B ON A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY 1, 3 DESC