SELECT O.CART_ID
FROM CART_PRODUCTS AS O
INNER JOIN
(
SELECT CART_ID,
       GROUP_CONCAT(NAME) as NAME
FROM CART_PRODUCTS
GROUP BY 1
) AS A ON O.CART_ID = A.CART_ID
WHERE A.NAME LIKE '%Milk%' AND A.NAME LIKE '%Yogurt%'
GROUP BY O.CART_ID
ORDER BY 1 ASC