SELECT ROOT.ID
FROM ECOLI_DATA AS ROOT
INNER JOIN 
(
    SELECT CHILD.ID
    FROM ECOLI_DATA AS PARENT
    INNER JOIN ECOLI_DATA AS CHILD ON PARENT.ID = CHILD.PARENT_ID
    WHERE CHILD.ID IS NOT NULL AND PARENT.PARENT_ID IS NULL
) AS FILTER ON ROOT.PARENT_ID = FILTER.ID
ORDER BY ROOT.ID