SELECT I.ANIMAL_ID,
       I.NAME
FROM ANIMAL_INS AS I
INNER JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.DATETIME IS NOT NULL AND I.DATETIME < O.DATETIME
ORDER BY DATEDIFF(I.DATETIME, O.DATETIME) ASC, I.DATETIME ASC
LIMIT 2