SELECT CRCC.CAR_ID,
       CRCC.CAR_TYPE,
       CAST(DAILY_FEE * 30 * ((100 - DISCOUNT_RATE) / 100) AS SIGNED) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CRCC
LEFT JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
) AS A ON CRCC.CAR_ID = A.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRCDP ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE
WHERE A.CAR_ID IS NULL AND CRCDP.DURATION_TYPE = '30일 이상' AND CRCC.CAR_TYPE IN('SUV', '세단')
GROUP BY 1, 2
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CRCC.CAR_TYPE ASC, CRCC.CAR_ID DESC