WITH RANKED_FAVORITE AS (
    SELECT FOOD_TYPE,
           REST_ID,
           REST_NAME,
           FAVORITES,
           RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RNK_FAV
    FROM REST_INFO
)
SELECT FOOD_TYPE,
       REST_ID,
       REST_NAME,
       FAVORITES
FROM RANKED_FAVORITE
WHERE RNK_FAV = 1
ORDER BY FOOD_TYPE DESC