SELECT FP.PRODUCT_ID,
       FP.PRODUCT_NAME,
       SUM(FP.PRICE * FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP
INNER JOIN FOOD_ORDER AS FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE FO.PRODUCE_DATE LIKE ('2022-05%')
GROUP BY 1, 2
ORDER BY 3 DESC, 1 ASC;