SELECT HISTORY_ID,
       ROUND(DAILY_FEE * DATE_DIFF * 
          (100 - IFNULL(DISCOUNT_RATE, 0)) / 100) AS FEE
FROM 
(
    SELECT HISTORY_ID,
           CAR_TYPE,
           DAILY_FEE,
           DATEDIFF(END_DATE, START_DATE) + 1 AS DATE_DIFF,
           CASE
               WHEN DATEDIFF(END_DATE, START_DATE) >= 90 THEN '90일 이상'
               WHEN DATEDIFF(END_DATE, START_DATE) >= 30 THEN '30일 이상'
               WHEN DATEDIFF(END_DATE, START_DATE) >= 7 THEN '7일 이상'
               ELSE '7일 미만'
           END DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR AS CRCC
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH ON CRCC.CAR_ID = CRCRH.CAR_ID
    WHERE CRCC.CAR_TYPE = '트럭'
) AS A
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRCDP 
ON A.CAR_TYPE = CRCDP.CAR_TYPE AND A.DURATION_TYPE = CRCDP.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC