SELECT HISTORY_ID,
       ROUND(DAILY_FEE * DATEDIFF * (100 - IFNULL(DISCOUNT_RATE, 0)) / 100) AS FEE
FROM (
    SELECT HISTORY_ID,
           CAR_TYPE,
           DAILY_FEE,
           DATEDIFF(END_DATE, START_DATE) + 1 AS DATEDIFF,
           CASE
               WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
               WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
               WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
               ELSE '7일 미만'
           END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR AS CRCC
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH ON CRCC.CAR_ID = CRCRH.CAR_ID
    WHERE CAR_TYPE = '트럭'
) AS A
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRCDP
ON A.CAR_TYPE = CRCDP.CAR_TYPE AND A.DURATION_TYPE = CRCDP.DURATION_TYPE
ORDER BY 2 DESC, 1 DESC