WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM HOURS
    WHERE HOUR < 23
)
SELECT H.HOUR,
       COUNT(A.DATETIME) AS COUNT
FROM HOURS AS H
LEFT JOIN ANIMAL_OUTS AS A ON H.HOUR = HOUR(A.DATETIME)
GROUP BY 1
ORDER BY 1 ASC
