SELECT ID,
       EMAIL,
       FIRST_NAME,
       LAST_NAME
FROM
(
SELECT D.ID,
       D.EMAIL,
       D.FIRST_NAME,
       D.LAST_NAME,
       GROUP_CONCAT(S.CATEGORY) AS CATEGORY
FROM DEVELOPERS AS D
INNER JOIN SKILLCODES AS S ON D.SKILL_CODE & S.CODE > 0
GROUP BY 1, 2, 3, 4
) AS A    
WHERE CATEGORY LIKE '%Front End%'
ORDER BY ID