SELECT YEAR(ED.DIFFERENTIATION_DATE) as YEAR,
       (A.MAX_YEAR_COLONY - ED.SIZE_OF_COLONY) as YEAR_DEV,
       ED.ID
FROM ECOLI_DATA as ED
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) as C_YEAR,
           MAX(SIZE_OF_COLONY) as MAX_YEAR_COLONY
    FROM ECOLI_DATA
    GROUP BY 1
) as A ON YEAR(ED.DIFFERENTIATION_DATE) = A.C_YEAR
ORDER BY 1, 2