SELECT SUM(hg.SCORE) as SCORE,
       he.EMP_NO,
       he.EMP_NAME,
       he.POSITION,
       he.EMAIL
FROM HR_DEPARTMENT as hd
INNER JOIN HR_EMPLOYEES as he ON hd.DEPT_ID = he.DEPT_ID
INNER JOIN HR_GRADE as hg ON he.EMP_NO = hg.EMP_NO
GROUP BY 2, 3, 4, 5
ORDER BY 1 DESC
LIMIT 1