SELECT CONCAT('/home/grep/src/', UGF.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS UGF
INNER JOIN 
(
SELECT UGB.BOARD_ID,
       MAX(VIEWS) as MAX_VIEW
FROM USED_GOODS_BOARD AS UGB
INNER JOIN USED_GOODS_FILE AS UGF ON UGB.BOARD_ID = UGF.BOARD_ID
GROUP BY 1
ORDER BY 2 DESC
LIMIT 1
) AS A ON UGF.BOARD_ID = A.BOARD_ID
ORDER BY FILE_ID DESC