SELECT FP.CATEGORY,
       MP.MAX_PRICE,
       FP.PRODUCT_NAME
FROM FOOD_PRODUCT AS FP
JOIN(
    SELECT CATEGORY,
        MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT 
    WHERE CATEGORY IN('과자', '국', '김치', '식용유')
    GROUP BY 1
) AS MP ON FP.CATEGORY = MP.CATEGORY AND FP.PRICE = MP.MAX_PRICE
WHERE FP.CATEGORY IN('과자', '국', '김치', '식용유')
ORDER BY 2 DESC

