SELECT CASE
           WHEN CATEGORY LIKE '%Front End%' AND NAME LIKE '%Python%' THEN 'A'
           WHEN NAME LIKE '%C#%' THEN 'B'
           WHEN CATEGORY LIKE '%Front End%' THEN 'C'
           ELSE NULL
       END AS GRADE,
       ID,
       EMAIL
FROM
(
SELECT D.ID,
       D.EMAIL,
       GROUP_CONCAT(S.NAME) AS NAME,
       GROUP_CONCAT(S.CATEGORY) AS CATEGORY
FROM DEVELOPERS AS D
JOIN SKILLCODES AS S ON D.SKILL_CODE & S.CODE = S.CODE
GROUP BY 1, 2
) AS A
GROUP BY ID, EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID